(define (lazy-count n)
  (cons n (delay (lazy-count (1+ n)))))
(define (lazip l)
  (cons (map car l) (delay (lazip (map force (map cdr l))))))
(define (lazy-pulse n t)
  (define (lazy-loop l)
    (cons (car l) (delay (lazy-loop (append (cdr l) `(,(car l)))))))
  (lazy-loop (reverse (cons t (make-list n #f)))))

(do ((l (lazip `( ,(lazy-pulse 100 #t)
                  ,(lazy-pulse  14 'fizzbuzz)
                  ,(lazy-pulse   2 'fizz)
                  ,(lazy-pulse   4 'buzz)
                  ,(lazy-count   1)))
        (force (cdr l))))
  ((caar l))
  (display (car (delete #f (car l))))
  (newline))
